name: Deploy website
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
          
      - name: cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm # cache le dossier des modules Node.js pour accélérer les installations futures
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }} # génère une clé de cache basée sur le contenu du fichier package-lock.json pour s'assurer que le cache est mis à jour lorsque les dépendances changent
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-files: ${{ steps.publish-js-filename.outputs.script-files }}
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm # cache le dossier des modules Node.js pour accélérer les installations futures
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }} # génère une clé de cache basée sur le contenu du fichier package-lock.json pour s'assurer que le cache est mis à jour lorsque les dépendances changent
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      
      - name: Publish JS filename
        id: publish-js-filename
        run: find dist/assets/*.js -type f -execdir echo '::set-output name=script-files::{}' ';' # permet de récupérer le nom du fichier JS généré et de le stocker dans une variable d'environnement pour les étapes suivantes
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: mon_artefact
          path: dist 
            
            
       
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Download build artifacts
        uses: actions/download-artifact@v8
        with:
          name: mon_artefact
          path: dist
      
      - name: List files
        run: ls -la dist

      - name: Output filename
        run: echo " ${{ needs.build.outputs.script-files }}" # permet d'afficher le nom du fichier JS généré dans les logs de l'étape de déploiement pour vérifier que la variable d'environnement a été correctement transmise depuis l'étape de build
      - name: Deploy
        run: echo "Deploying..."
          